title: Welcome to Tom's World
description: A starting point for all my stuff
title2: Aasland Technologies Blog
description2: Tech adventures
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
